name 			= "Smart Jetpack"; // Name of your mod
author 		= "SLE / klockhov"; // Affects Arma 3 Launcher, when the mod are loaded as local
logo 			= "ModIcons\sle_jet_logo.paa"; // Logo displayed in the main menu
logoOver 		= "ModIcons\sle_jet_logo_hover.paa"; // When the mouse is over, in the main menu
tooltip 		= "Smart Jetpack";
tooltipOwned 	= "Smart Jetpack"; // Tool tip displayed when the mouse is left over, in the main menu
picture 		= "ModIcons\sle_jet_picture.paa"; // Picture displayed from the expansions menu. Optimal size is 2048x1024
actionName 	= "GitHub";
action 		= "https://github.com/Etaselia/3rd-Rangers/tree/Development"; // Website URL, that can be accessed from the expansions menu
overview 		= "This mod adds advanced jetpack capable of autolanding, hovering in place, projecting flight path vector, projecting Continuously calculated impact position. Also highly customizable."; // Supports structured text
hideName 		= 0; // Hide the extension name
hidePicture	= 0;	// Hide the extension menu
dlcColor[] 	= {0,1,0,1}; // Color used for DLC stripes and backgrounds (RGBA)
logoSmall 		= "ModIcons\sle_jet_logo_small.paa"; // Display in creative lists, next to the entities added by the mod
